/**
 * Prints the dialect model as TypeScript: `src/generated/enums.ts` and `src/generated/messages.ts`.
 * Output is formatted with the repository's Prettier config so it passes `prettier --check`.
 */
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { format, resolveConfig } from 'prettier'
import type { FieldType } from '../src/descriptor.js'
import { loadDialect, type Dialect, type EnumDefinition, type FieldDefinition, type MessageDefinition } from './definitions.js'

export const PACKAGE_DIR = join(dirname(fileURLToPath(import.meta.url)), '..')
export const DEFINITIONS_DIR = join(PACKAGE_DIR, 'definitions')
export const GENERATED_DIR = join(PACKAGE_DIR, 'src', 'generated')
export const ROOT_DEFINITION = 'all.xml'

const HEADER = (dialect: Dialect): string =>
  [
    '// Generated by packages/mavlink/scripts/generate.ts from definitions/' + ROOT_DEFINITION + ' (and',
    '// ' + dialect.files.filter((f) => f !== ROOT_DEFINITION).join(', ') + ').',
    '// Do not edit: change the generator or the definitions and run `npm run generate`.',
    ''
  ].join('\n')

/** `MAV_CMD` -> `MavCmd`, `GPS2_RAW` -> `Gps2Raw`. */
export function pascalCase(name: string): string {
  return name
    .toLowerCase()
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

/** XML field name to the camelCase key used in TypeScript: `time_boot_ms` -> `timeBootMs`, `Vcc` -> `vcc`. */
export function camelCase(name: string): string {
  const [first = '', ...rest] = name.split('_').filter((part) => part !== '')
  const head = /[a-z]/.test(first) ? first.charAt(0).toLowerCase() + first.slice(1) : first.toLowerCase()
  return head + rest.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join('')
}

const TYPED_ARRAY: Readonly<Record<Exclude<FieldType, 'char'>, string>> = {
  int8_t: 'Int8Array',
  uint8_t: 'Uint8Array',
  int16_t: 'Int16Array',
  uint16_t: 'Uint16Array',
  int32_t: 'Int32Array',
  uint32_t: 'Uint32Array',
  float: 'Float32Array',
  double: 'Float64Array',
  int64_t: 'BigInt64Array',
  uint64_t: 'BigUint64Array'
}

/** Escapes text for a JSDoc block and wraps it to a readable width. */
function wrap(text: string, width = 110): string[] {
  const words = text.replace(/\*\//g, '*\\/').split(/\s+/).filter(Boolean)
  const lines: string[] = []
  let line = ''
  for (const word of words) {
    if (line !== '' && line.length + 1 + word.length > width) {
      lines.push(line)
      line = word
    } else {
      line = line === '' ? word : `${line} ${word}`
    }
  }
  if (line !== '') lines.push(line)
  return lines
}

/** A JSDoc comment from paragraphs (empty ones dropped). */
function jsdoc(paragraphs: readonly (string | undefined)[], indent = ''): string {
  const blocks = paragraphs.filter((p): p is string => p !== undefined && p.trim() !== '').map((p) => wrap(p))
  if (blocks.length === 0) return ''
  const first = blocks[0]
  if (blocks.length === 1 && first?.length === 1) return `${indent}/** ${first[0] ?? ''} */\n`
  const body = blocks.map((lines) => lines.map((l) => `${indent} * ${l}`).join('\n')).join(`\n${indent} *\n`)
  return `${indent}/**\n${body}\n${indent} */\n`
}

interface Names {
  readonly enumConst: ReadonlyMap<string, string>
  readonly messageInterface: ReadonlyMap<string, string>
}

/** Checks that generated identifiers cannot collide with each other or with the hand-written API. */
function assignNames(dialect: Dialect): Names {
  const reserved = new Set(['Message', 'MessageMap', 'MessageName', 'MessageIdMap', 'ExtensionFieldMap', 'Mavlink1MessageName'])
  const taken = new Map<string, string>()
  const claim = (identifier: string, owner: string): string => {
    const previous = taken.get(identifier)
    if (previous !== undefined || reserved.has(identifier))
      throw new Error(`${owner} and ${previous ?? 'the runtime'} both map to ${identifier}`)
    taken.set(identifier, owner)
    return identifier
  }
  const enumConst = new Map(dialect.enums.map((e) => [e.name, claim(pascalCase(e.name), `enum ${e.name}`)]))
  const messageInterface = new Map(dialect.messages.map((m) => [m.name, claim(pascalCase(m.name), `message ${m.name}`)]))
  for (const message of dialect.messages) {
    claim(message.name, `descriptor ${message.name}`)
    const keys = new Set(message.fields.map((f) => camelCase(f.name)))
    if (keys.size !== message.fields.length) throw new Error(`${message.name}: camelCase field names collide`)
  }
  return { enumConst, messageInterface }
}

function emitEnums(dialect: Dialect, names: Names): string {
  const out: string[] = [HEADER(dialect)]
  for (const definition of dialect.enums) {
    const constName = names.enumConst.get(definition.name) ?? definition.name
    out.push(
      jsdoc([
        definition.description,
        definition.deprecated,
        definition.bitmask ? 'Bitmask: fields of this type hold a bitwise OR of these flags, typed as plain numbers.' : undefined,
        `MAVLink enum \`${definition.name}\`.`
      ])
    )
    out.push(`export const ${constName} = {\n`)
    for (const entry of definition.entries) {
      const params = entry.params
        .filter((p) => p.description !== '' || p.label !== '')
        .map((p) => `Param ${p.index}${p.label === '' ? '' : ` (${p.label})`}: ${p.description}`)
      out.push(jsdoc([entry.description, entry.deprecated, ...params], '  '))
      out.push(`  ${entry.name}: ${entry.value},\n`)
    }
    out.push(`} as const\n`)
    out.push(`/** A value of {@link ${constName}}. */\n`)
    out.push(`export type ${constName} = (typeof ${constName})[keyof typeof ${constName}]\n\n`)
  }
  return out.join('')
}

function isBitmask(field: FieldDefinition, enums: ReadonlyMap<string, EnumDefinition>): boolean {
  return field.displayBitmask || (field.enumName !== undefined && enums.get(field.enumName)?.bitmask === true)
}

function fieldType(field: FieldDefinition, enums: ReadonlyMap<string, EnumDefinition>, names: Names): string {
  if (field.type === 'char') return 'string'
  if (field.arrayLength > 0) return TYPED_ARRAY[field.type]
  if (field.type === 'int64_t' || field.type === 'uint64_t') return 'bigint'
  if (field.enumName !== undefined && !isBitmask(field, enums)) {
    const name = names.enumConst.get(field.enumName)
    if (name !== undefined && (enums.get(field.enumName)?.entries.length ?? 0) > 0) return name
  }
  return 'number'
}

function emitMessage(
  message: MessageDefinition,
  enums: ReadonlyMap<string, EnumDefinition>,
  names: Names,
  usedEnums: Set<string>
): string {
  const interfaceName = names.messageInterface.get(message.name) ?? message.name
  const out: string[] = []
  out.push(
    jsdoc([
      message.description,
      message.deprecated,
      message.workInProgress ? 'Work in progress: may change without notice.' : undefined,
      `MAVLink message \`${message.name}\` (id ${message.id}).`
    ])
  )
  out.push(`export interface ${interfaceName} {\n`)
  for (const field of message.fields) {
    const enumConst = field.enumName === undefined ? undefined : names.enumConst.get(field.enumName)
    const bitmask = isBitmask(field, enums)
    out.push(
      jsdoc(
        [
          field.description,
          field.units === undefined ? undefined : `Units: ${field.units}.`,
          enumConst !== undefined && bitmask ? `Bitmask of {@link ${enumConst}} flags.` : undefined,
          field.extension ? 'MAVLink 2 extension: 0 when the sender omitted it.' : undefined,
          `\`${field.name}\`: ${field.type}${field.arrayLength > 0 ? `[${field.arrayLength}]` : ''}`
        ],
        '  '
      )
    )
    out.push(`  readonly ${camelCase(field.name)}: ${fieldType(field, enums, names)}\n`)
  }
  out.push('}\n\n')

  out.push(`/** Descriptor of {@link ${interfaceName}} (\`${message.name}\`, id ${message.id}). */\n`)
  out.push(`export const ${message.name}: MessageDescriptor<'${message.name}'> = {\n`)
  out.push(
    `  id: ${message.id},\n  name: '${message.name}',\n  crcExtra: ${message.crcExtra},\n  baseLength: ${message.baseLength},\n  length: ${message.length},\n`
  )
  out.push('  fields: [\n')
  for (const field of message.fields) {
    const parts = [`name: '${camelCase(field.name)}'`, `type: '${field.type}'`, `offset: ${field.offset}`]
    if (field.arrayLength > 0) parts.push(`arrayLength: ${field.arrayLength}`)
    if (field.extension) parts.push('extension: true')
    const enumConst = field.enumName === undefined ? undefined : names.enumConst.get(field.enumName)
    if (enumConst !== undefined && field.enumName !== undefined) {
      usedEnums.add(enumConst)
      parts.push(`enum: ${enumConst}`)
    }
    if (isBitmask(field, enums)) parts.push('bitmask: true')
    out.push(`    { ${parts.join(', ')} },\n`)
  }
  out.push('  ]\n}\n\n')
  return out.join('')
}

function emitMessages(dialect: Dialect, names: Names): string {
  const enums = new Map(dialect.enums.map((e) => [e.name, e]))
  const usedEnums = new Set<string>()
  const body = dialect.messages.map((m) => emitMessage(m, enums, names, usedEnums)).join('')
  const iface = (m: MessageDefinition): string => names.messageInterface.get(m.name) ?? m.name

  const out: string[] = [HEADER(dialect)]
  out.push(`import type { MessageDescriptor } from '../descriptor.js'\n`)
  out.push(`import { ${[...usedEnums].sort().join(', ')} } from './enums.js'\n\n`)
  out.push(body)
  out.push('/** Message name to its fields interface. */\nexport interface MessageMap {\n')
  for (const m of dialect.messages) out.push(`  ${m.name}: ${iface(m)}\n`)
  out.push('}\n\n/** Name of a message in the dialect. */\nexport type MessageName = keyof MessageMap\n\n')
  out.push('/** Message name to its id. */\nexport interface MessageIdMap {\n')
  for (const m of dialect.messages) out.push(`  ${m.name}: ${m.id}\n`)
  out.push('}\n\n')
  out.push(
    '/** Message name to the keys of its MAVLink 2 extension fields (optional when encoding). */\nexport interface ExtensionFieldMap {\n'
  )
  for (const m of dialect.messages) {
    const keys = m.fields.filter((f) => f.extension).map((f) => `'${camelCase(f.name)}'`)
    out.push(`  ${m.name}: ${keys.length === 0 ? 'never' : keys.join(' | ')}\n`)
  }
  out.push('}\n\n')
  out.push('/** Messages whose id fits in a MAVLink 1 header (0-255). */\nexport type Mavlink1MessageName =\n')
  out.push(
    dialect.messages
      .filter((m) => m.id < 256)
      .map((m) => `  | '${m.name}'`)
      .join('\n') + '\n\n'
  )
  out.push(
    '/**\n * Every message in the dialect, by ascending id. Importing this pulls every descriptor into a bundle;\n * import individual descriptors instead to keep only the messages you use.\n */\n'
  )
  out.push('export const ALL_MESSAGES: readonly MessageDescriptor<MessageName>[] = [\n')
  for (const m of dialect.messages) out.push(`  ${m.name},\n`)
  out.push(']\n')
  return out.join('')
}

/** Id, name and CRC_EXTRA only: what framing-only tools need, without the layouts. */
function emitTable(dialect: Dialect): string {
  const out: string[] = [HEADER(dialect)]
  out.push(
    '/**\n * Id, name and CRC_EXTRA of every message, by ascending id: enough to frame and checksum MAVLink\n * without decoding it, at a fraction of the size of the full descriptors.\n */\n'
  )
  out.push('export const MESSAGE_TABLE = [\n')
  for (const m of dialect.messages) out.push(`  { id: ${m.id}, name: '${m.name}', crcExtra: ${m.crcExtra} },\n`)
  out.push('] as const satisfies readonly { readonly id: number; readonly name: string; readonly crcExtra: number }[]\n')
  return out.join('')
}

/** Generated file name (relative to `src/generated`) to its formatted contents. */
export async function generateSources(): Promise<Map<string, string>> {
  const dialect = loadDialect(DEFINITIONS_DIR, ROOT_DEFINITION)
  const names = assignNames(dialect)
  const sources = new Map([
    ['enums.ts', emitEnums(dialect, names)],
    ['messages.ts', emitMessages(dialect, names)],
    ['table.ts', emitTable(dialect)]
  ])
  const formatted = new Map<string, string>()
  for (const [file, source] of sources) {
    const path = join(GENERATED_DIR, file)
    const options = (await resolveConfig(path)) ?? {}
    formatted.set(file, await format(source, { ...options, filepath: path }))
  }
  return formatted
}
