/**
 * Test-only: runs upstream `modules/MAVLink/mavlink.js` (pymavlink-generated, with its runtime
 * fixes) in a `node:vm` context so this package can be compared with it on identical bytes.
 * Upstream takes its Node path (CommonJS `require` of jspack, `events`, `util`), so
 * `mavlink20.ready` is already resolved; it is awaited anyway, as its README requires.
 */
import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createContext, runInContext } from 'node:vm'

const UPSTREAM_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '../../../../upstream')
export const UPSTREAM_MAVLINK = resolve(UPSTREAM_DIR, 'modules/MAVLink/mavlink.js')

/** Fixtures generated by `upstream/tests/fixtures/generate_mavlink.py` with pymavlink. */
export interface MavlinkFixtures {
  readonly messages: readonly {
    readonly name: string
    readonly fields: Readonly<Record<string, number | string | number[]>>
    readonly hex: string
  }[]
  readonly signed: string
  readonly v1: string
}

export function loadFixtures(): MavlinkFixtures {
  return JSON.parse(readFileSync(resolve(UPSTREAM_DIR, 'tests/fixtures/mavlink.json'), 'utf8')) as MavlinkFixtures
}

/** An upstream decoded message: fields by snake_case name plus underscore-prefixed metadata. */
export interface UpstreamMessage {
  readonly _name: string
  readonly _id: number
  readonly fieldnames: readonly string[]
  readonly [field: string]: unknown
  pack(processor: UpstreamProcessor): number[]
}

/** Upstream `mavlink20.header` of a decoded message. */
export interface UpstreamHeader {
  readonly mlen: number
  readonly seq: number
  readonly srcSystem: number
  readonly srcComponent: number
  readonly msgId: number
  readonly incompat_flags: number
  readonly compat_flags: number
}

/** Upstream `MAVLinkSigning`. */
export interface UpstreamSigning {
  secret_key: Uint8Array
  timestamp: number
  link_id: number
  sign_outgoing: boolean
  allow_unsigned_callback: ((processor: UpstreamProcessor, msgId: number) => boolean) | undefined
  stream_timestamps: Record<string, number>
  readonly sig_count: number
  readonly badsig_count: number
  readonly goodsig_count: number
  readonly unsigned_count: number
  readonly reject_count: number
}

export interface UpstreamProcessor {
  seq: number
  readonly signing: UpstreamSigning
  readonly total_packets_received: number
  readonly total_bytes_received: number
  readonly total_receive_errors: number
  decode(frame: Uint8Array): UpstreamMessage
  parseBuffer(bytes: Uint8Array | null): UpstreamMessage[] | null
}

export interface UpstreamMapEntry {
  readonly format: string
  readonly order_map: readonly number[]
  readonly crc_extra: number
  readonly type: new () => UpstreamMessage
}

export interface UpstreamMavlink {
  readonly mavlink20: {
    readonly map: Readonly<Record<string, UpstreamMapEntry>>
    readonly ready: Promise<void>
    readonly messages: Readonly<Record<string, new (...args: unknown[]) => UpstreamMessage>>
    sha256(input: Uint8Array): Uint8Array
    create_signature(key: Uint8Array, data: Uint8Array): Uint8Array
  }
  readonly MAVLink20Processor: new (logger: null, srcSystem: number, srcComponent: number) => UpstreamProcessor
}

/** The parts of an upstream processor that `applyResyncTodo` patches. */
interface UpstreamProcessorInternals {
  buf: Uint8Array
  bufInError: Uint8Array
  parsePayload(): UpstreamMessage | null
  concat_buffer(a: Uint8Array, b: Uint8Array): Uint8Array
}

function hasInternals(value: object): value is UpstreamProcessorInternals {
  return 'parsePayload' in value && 'concat_buffer' in value && 'buf' in value
}

/**
 * Applies the TODO in upstream's own `parsePayload` (`mavlink.js:19178-19180`) to one processor:
 * "if the message is not well formed (correct prefix by accident), cut-off 1 char only". When
 * `decode` fails on the frame checksum or on unsupported incompatibility flags, only the start
 * marker is reported (as BAD_DATA) and dropped, and the rest of the bytes taken go back in front of
 * the buffer. Everything else is upstream's code unchanged. This is the oracle for the port's fix of
 * proven upstream bug #150 (see `docs/bug-proofs/mavlink.md`).
 */
export function applyResyncTodo(processor: UpstreamProcessor): UpstreamProcessor {
  if (!hasInternals(processor)) throw new Error('not an upstream MAVLink20Processor')
  const original = processor.parsePayload.bind(processor)
  processor.parsePayload = () => {
    try {
      return original()
    } catch (error) {
      // The error comes from the vm's realm, so `instanceof Error` would be false.
      const message = typeof error === 'object' && error !== null && 'message' in error ? String(error.message) : ''
      if (/^(invalid MAVLink CRC|Unsupported MAVLink incompatibility flags)/.test(message)) {
        const taken = processor.bufInError
        processor.buf = processor.concat_buffer(taken.slice(1), processor.buf)
        processor.bufInError = taken.slice(0, 1)
      }
      throw error
    }
  }
  return processor
}

function isUpstream(value: unknown): value is UpstreamMavlink {
  return typeof value === 'object' && value !== null && 'mavlink20' in value && 'MAVLink20Processor' in value
}

export async function loadUpstream(): Promise<UpstreamMavlink> {
  const module = { exports: {} as unknown }
  const sandbox: Record<string, unknown> = { require: createRequire(UPSTREAM_MAVLINK), module, process, console, Buffer }
  sandbox.global = sandbox
  const context = createContext(sandbox)
  runInContext(readFileSync(UPSTREAM_MAVLINK, 'utf8'), context, { filename: UPSTREAM_MAVLINK })
  const exported = module.exports
  if (!isUpstream(exported)) throw new Error('upstream mavlink.js did not export mavlink20')
  await exported.mavlink20.ready
  return exported
}

/**
 * Upstream's enums as mavgen printed them: each `// NAME` comment in the `// enums` section starts an
 * enum, followed by `mavlink20.ENTRY = value` lines (including mavgen's `NAME_ENUM_END`).
 */
export function loadUpstreamEnums(): Map<string, Map<string, number>> {
  const lines = readFileSync(UPSTREAM_MAVLINK, 'utf8').split('\n')
  const enums = new Map<string, Map<string, number>>()
  let current: Map<string, number> | undefined
  for (const line of lines.slice(lines.indexOf('// enums') + 1, lines.indexOf('// message IDs'))) {
    const heading = /^\/\/ ([A-Za-z0-9_]+)$/.exec(line)
    const entry = /^mavlink20\.([A-Za-z0-9_]+) = (\d+)/.exec(line)
    if (heading !== null) {
      current = new Map()
      enums.set(heading[1]!, current)
    } else if (entry !== null) {
      if (current === undefined) throw new Error(`enum entry outside an enum: ${line}`)
      current.set(entry[1]!, Number(entry[2]))
    }
  }
  return enums
}
