/**
 * Test-only: runs upstream `modules/MAVLink/mavlink.js` (pymavlink-generated, with its runtime
 * fixes) in a `node:vm` context so this package can be compared with it on identical bytes.
 * Upstream takes its Node path (CommonJS `require` of jspack, `events`, `util`), so
 * `mavlink20.ready` is already resolved; it is awaited anyway, as its README requires.
 */
import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createContext, runInContext } from 'node:vm'

const UPSTREAM_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '../../../../upstream')
export const UPSTREAM_MAVLINK = resolve(UPSTREAM_DIR, 'modules/MAVLink/mavlink.js')

/** Fixtures generated by `upstream/tests/fixtures/generate_mavlink.py` with pymavlink. */
export interface MavlinkFixtures {
  readonly messages: readonly {
    readonly name: string
    readonly fields: Readonly<Record<string, number | string | number[]>>
    readonly hex: string
  }[]
  readonly signed: string
  readonly v1: string
}

export function loadFixtures(): MavlinkFixtures {
  return JSON.parse(readFileSync(resolve(UPSTREAM_DIR, 'tests/fixtures/mavlink.json'), 'utf8')) as MavlinkFixtures
}

/** An upstream decoded message: fields by snake_case name plus underscore-prefixed metadata. */
export interface UpstreamMessage {
  readonly _name: string
  readonly _id: number
  readonly fieldnames: readonly string[]
  readonly [field: string]: unknown
  pack(processor: UpstreamProcessor): number[]
}

export interface UpstreamProcessor {
  seq: number
  decode(frame: Uint8Array): UpstreamMessage
}

export interface UpstreamMapEntry {
  readonly format: string
  readonly order_map: readonly number[]
  readonly crc_extra: number
  readonly type: new () => UpstreamMessage
}

export interface UpstreamMavlink {
  readonly mavlink20: { readonly map: Readonly<Record<string, UpstreamMapEntry>>; readonly ready: Promise<void> }
  readonly MAVLink20Processor: new (logger: null, srcSystem: number, srcComponent: number) => UpstreamProcessor
}

function isUpstream(value: unknown): value is UpstreamMavlink {
  return typeof value === 'object' && value !== null && 'mavlink20' in value && 'MAVLink20Processor' in value
}

export async function loadUpstream(): Promise<UpstreamMavlink> {
  const module = { exports: {} as unknown }
  const sandbox: Record<string, unknown> = { require: createRequire(UPSTREAM_MAVLINK), module, process, console, Buffer }
  sandbox.global = sandbox
  const context = createContext(sandbox)
  runInContext(readFileSync(UPSTREAM_MAVLINK, 'utf8'), context, { filename: UPSTREAM_MAVLINK })
  const exported = module.exports
  if (!isUpstream(exported)) throw new Error('upstream mavlink.js did not export mavlink20')
  await exported.mavlink20.ready
  return exported
}
