/**
 * Option forms the menu and sub grid widgets always use (upstream Widgets/Menu.js and
 * Widgets/SubGrid.js), verbatim: they are saved into layouts with the widget.
 */
import type { JsonObject } from '../layout/json.js'

export const MENU_FORM: JsonObject = {
  components: [
    {
      label: 'Border color',
      key: 'borderColor',
      type: 'color',
      input: true,
      tableView: false,
      widget: { type: 'input' },
      inputType: 'color',
      mask: false,
      data: '#000000',
      defaultValue: '#c8c8c8',
      id: 'ebao4j',
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      protected: false,
      unique: false,
      persistent: true,
      hidden: false,
      clearOnHide: true,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      disabled: false,
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      attributes: {},
      validateOn: 'change',
      validate: {
        required: false,
        custom: '',
        customPrivate: false,
        strictDateValidation: false,
        multiple: false,
        unique: false
      },
      conditional: { show: null, when: null, eq: '' },
      overlay: { style: '', left: '', top: '', width: '', height: '' },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      addons: []
    },
    {
      label: 'Background color',
      tooltip: 'Note that the icons may not show up if the background is too dark.',
      key: 'backgroundColor',
      type: 'color',
      input: true,
      tableView: false,
      widget: { type: 'input' },
      inputType: 'color',
      mask: false,
      data: '#000000',
      defaultValue: '#ffffff',
      id: 'e6byhel',
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      protected: false,
      unique: false,
      persistent: true,
      hidden: false,
      clearOnHide: true,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      hideLabel: false,
      tabindex: '',
      disabled: false,
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      attributes: {},
      validateOn: 'change',
      validate: {
        required: false,
        custom: '',
        customPrivate: false,
        strictDateValidation: false,
        multiple: false,
        unique: false
      },
      conditional: { show: null, when: null, eq: '' },
      overlay: { style: '', left: '', top: '', width: '', height: '' },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      addons: []
    }
  ]
}

export const SUBGRID_FORM: JsonObject = {
  components: [
    {
      label: 'Rows',
      tooltip: 'Number of rows in this subgrid.',
      applyMaskOn: 'change',
      mask: false,
      tableView: false,
      delimiter: false,
      requireDecimal: false,
      inputFormat: 'plain',
      truncateMultipleSpaces: false,
      validate: { min: 1, max: 12 },
      validateWhenHidden: false,
      key: 'rows',
      type: 'number',
      input: true,
      defaultValue: 2,
      decimalLimit: 0
    },
    {
      label: 'Columns',
      tooltip: 'Number of columns in this subgrid.',
      applyMaskOn: 'change',
      mask: false,
      tableView: false,
      delimiter: false,
      requireDecimal: false,
      inputFormat: 'plain',
      truncateMultipleSpaces: false,
      validate: { min: 1, max: 12 },
      validateWhenHidden: false,
      key: 'columns',
      type: 'number',
      input: true,
      defaultValue: 2,
      decimalLimit: 0
    },
    {
      label: 'Border color',
      key: 'borderColor',
      type: 'color',
      input: true,
      tableView: false,
      widget: { type: 'input' },
      inputType: 'color',
      mask: false,
      data: '#000000',
      defaultValue: '#c8c8c8',
      id: 'ebao4j',
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      protected: false,
      unique: false,
      persistent: true,
      hidden: false,
      clearOnHide: true,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      disabled: false,
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      attributes: {},
      validateOn: 'change',
      validate: {
        required: false,
        custom: '',
        customPrivate: false,
        strictDateValidation: false,
        multiple: false,
        unique: false
      },
      conditional: { show: null, when: null, eq: '' },
      overlay: { style: '', left: '', top: '', width: '', height: '' },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      addons: []
    },
    {
      label: 'Background color',
      tooltip: '',
      key: 'backgroundColor',
      type: 'color',
      input: true,
      tableView: false,
      widget: { type: 'input' },
      inputType: 'color',
      mask: false,
      data: '#000000',
      defaultValue: '#ffffff',
      id: 'e6byhel',
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      protected: false,
      unique: false,
      persistent: true,
      hidden: false,
      clearOnHide: true,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      hideLabel: false,
      tabindex: '',
      disabled: false,
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      attributes: {},
      validateOn: 'change',
      validate: {
        required: false,
        custom: '',
        customPrivate: false,
        strictDateValidation: false,
        multiple: false,
        unique: false
      },
      conditional: { show: null, when: null, eq: '' },
      overlay: { style: '', left: '', top: '', width: '', height: '' },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      addons: []
    },
    {
      label: 'Background image',
      tooltip:
        'The sub grid will take on the aspect ratio of the image so sub grid widgets hold position relative to the image as the dashboard is re-sized.',
      storage: 'base64',
      key: 'backgroundImage',
      type: 'file',
      input: true
    }
  ]
}
